### ISSUE TITLE
Add support for Meteor 3.0

### ISSUE THREAD

**Issue by dallman2** [VeliovGroup/Meteor-Cookies#21] opened 2024-02-06 23:05 UTC
Hello,

Currently, this package uses the API version call `api.versionsFrom('1.4')`. This causes dependancy version conflicts with other packages. Is there a plan to update this package to use the following API level call: `api.versionsFrom(['1.4', '3.0-beta.0']);`?

Thanks

**Comment by dr-dimitru** [comment] 2024-02-07 12:17
Hello @dallman2 yes, this week I'm going to upgrade/update most of my packages prior 3.0 launch
Starting with dependencies of `ostrio:files` (e.g. this library)

**Comment by dallman2** [comment] 2024-02-07 19:13
@dr-dimitru I didn't notice that you also maintained this library 😂. Thanks!

**Comment by dr-dimitru** [comment] 2024-02-09 22:52
@dallman2 it's out! Please let me know how tests goes at your end

**Comment by dallman2** [comment] 2024-02-09 23:15
@dr-dimitru found one issue, the `fetch` requirement conflicts with the `fetch` version that meteor's `dynamic-import` uses. I modified my local `cookies` clone to have `api.use('fetch@0.1.4-beta300.0', 'client');` rather than the existing `api.use('fetch@0.1.4', 'client');` and it solved the problem.

**Comment by dr-dimitru** [comment] 2024-02-09 23:19
@dallman2 I ran tests locally as well, but haven't experienced such issue, are you on `meteor@3.0-beta.0` or older version?

**Comment by dallman2** [comment] 2024-02-09 23:21
I am on the `beta.0` branch. Here was my original error output:

```
   While selecting package versions:
   error: Conflict: Constraint fetch@0.1.4 is not satisfied by fetch 0.1.4-beta300.0.
   Constraints on package "fetch":
   * fetch@~0.1.4-beta300.0 <- top level
   * fetch@0.1.4-beta300.0 <- dynamic-import 0.7.4-beta300.0
   * fetch@0.1.4 || 0.1.4-beta300.0 <- ostrio:files 2.3.3
   * fetch@0.1.4 <- ostrio:cookies 2.8.0
   ```

Edit: Removing the version specifier on `fetch` entirely fixed it as well; ie `api.use('fetch', 'client');`. The strange thing is that the meteor `dynamic-import` package makes no specification on the version of `fetch` it requires in the `beta.0` branch...

**Comment by dr-dimitru** [comment] 2024-02-09 23:25
> Edit: Removing the version specifier on fetch entirely fixed it as well; ie api.use('fetch', 'client');

@dallman2 yes, but `meteor publish` doesn't let to publish without version constraint

**Comment by dr-dimitru** [comment] 2024-02-09 23:30
@dallman2 going to wait for more reports. If anything, I'll update it to:
```js
api.use('fetch@0.1.4 || 0.1.4-beta300.0')
```

Let me know if you're able to try it at your end

**Comment by dr-dimitru** [comment] 2024-02-09 23:31
> Here was my original error output:

@dallman2  looking at console output — I'd say it can get solved by upgrading [`ostrio:files@3.0.0-beta.4`](https://packosphere.com/ostrio/files/3.0.0-beta.4)

**Comment by dallman2** [comment] 2024-02-09 23:34
> > Here was my original error output:
> 
> @dallman2 looking at console output — I'd say it can get solved by upgrading [`ostrio:files@3.0.0-beta.4`](https://packosphere.com/ostrio/files/3.0.0-beta.4)

I will do that upgrade, but it was `dynamic-import` that was only compatible with `fetch@0.1.4-beta300.0`. The `||` syntax fix in your previous reply works though. Thanks! I will post in the `ostrio:files` repo when I get beta 4 running locally.

**Comment by harryadel** [comment] 2024-02-19 10:33
@dr-dimitru There's a little issue as I'm trying to update to 3.0

Thank you for the latest release where you added support for 3.0
https://github.com/veliovgroup/meteor-cookies/blob/3d776a812d6e1918e588f83ea4b8d07a00596698/package.js#L10

The problem is you fix the fetch package version to 1.4 which is incompatible with 3.0 as it uses 0.1.4-beta300.0 
https://github.com/veliovgroup/meteor-cookies/blob/3d776a812d6e1918e588f83ea4b8d07a00596698/package.js#L13

I'd appreciate a quick fix on this one, please. Thank you for your efforts :pray:  

![Screenshot_2024-02-19_12-32-17](https://github.com/veliovgroup/meteor-cookies/assets/6644545/1880af24-951c-4ee4-bbe8-3e68d75b55ee)

**Comment by dokithonon** [comment] 2024-03-02 21:11
Hello,
I think I have a similar challenge.
I try to update to 

`meteor update --release 3.0-beta.6`

It says that there is a conflict

```
Conflict: Constraint fetch@0.1.4 is not satisfied by fetch 0.1.4-beta300.6.
Constraints on package "fetch":
* fetch@0.1.4-beta300.6 <- top level
* fetch@~0.1.4-beta300.6 <- top level
* fetch@0.1.4-beta300.6 <- dynamic-import 0.7.4-beta300.6 <- ecmascript 0.16.8-beta300.6
* fetch@0.1.4 || 0.1.4-beta300.0 <- ostrio:files 3.0.0-beta.4
* fetch@0.1.4 <- ostrio:cookies 2.8.0 <- ostrio:files 3.0.0-beta.4
* fetch@0.1.4-alpha300.18 <- montiapm:agent 3.0.0-beta.4
```

Has anyone found a solution ?

**Comment by dallman2** [comment] 2024-03-05 20:20
I have this package cloned on my machine currently. My temporary solution is to change `api.use('fetch@0.1.4', 'client');` to `api.use('fetch@0.1.4 || 0.1.4-beta300.0', 'client');` in the `package.js`.

**Comment by dr-dimitru** [comment] 2024-03-16 19:10
@dallman2 pushed as [`v2.8.1`](https://github.com/veliovgroup/meteor-cookies/releases/tag/2.8.1)

Feel free to close it in case if the issue is solved on your end.

**Closed as completed** 2024-03-18 22:03 UTC
Labels: question
